/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#eef0ff",
        "surface-container-lowest": "#ffffff",
        secondary: "#3d48d9",
        "secondary-fixed-dim": "#bec2ff",
        "surface-container-high": "#e2e7ff",
        "on-background": "#131b2e",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        tertiary: "#4e4e58",
        "tertiary-container": "#666670",
        "on-tertiary-container": "#e7e5f1",
        "tertiary-fixed-dim": "#c7c5d1",
        "surface-variant": "#dae2fd",
        "outline-variant": "#ccc3d8",
        background: "#faf8ff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#1a1b23",
        "on-surface-variant": "#4a4455",
        "on-surface": "#131b2e",
        "error-container": "#ffdad6",
        "inverse-surface": "#283044",
        "surface-tint": "#732ee4",
        "tertiary-fixed": "#e3e1ed",
        "surface-container-highest": "#dae2fd",
        "on-primary-fixed": "#25005a",
        "on-secondary-fixed": "#00046a",
        surface: "#faf8ff",
        outline: "#7b7487",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fffbff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#46464f",
        "surface-container": "#eaedff",
        "primary-fixed": "#eaddff",
        "primary-container": "#7c3aed",
        "inverse-primary": "#d2bbff",
        "primary-fixed-dim": "#d2bbff",
        primary: "#630ed4",
        "surface-bright": "#faf8ff",
        "on-primary-fixed-variant": "#5a00c6",
        "surface-container-low": "#f2f3ff",
        "surface-dim": "#d2d9f4",
        "secondary-container": "#5864f3",
        "on-secondary-fixed-variant": "#222ec4",
        "on-primary-container": "#ede0ff",
        "secondary-fixed": "#e0e0ff",
        "glass-border": "rgba(204, 195, 216, 0.3)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        ROUND_EIGHT: "0.5rem",
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        "margin-tablet": "32px",
        base: "8px",
        "container-max": "1280px",
        "section-gap": "120px",
      },
      fontFamily: {
        "display-lg": ["Sora"],
        "headline-lg": ["Sora"],
        "body-lg": ["Inter"],
        "headline-xl": ["Sora"],
        "display-lg-mobile": ["Sora"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        headline: ["Sora"],
        display: ["Sora"],
        body: ["Inter"],
        label: ["Inter"],
        "label-sm": ["Inter"],
        sora: ["Sora"],
      },
      fontSize: {
        "display-lg": ["64px", {
          lineHeight: "1.1",
          letterSpacing: "-0.02em",
          fontWeight: "700",
        }],
        "headline-lg": ["28px", {
          lineHeight: "1.4",
          fontWeight: "600",
        }],
        "body-lg": ["18px", {
          lineHeight: "1.6",
          fontWeight: "400",
        }],
        "headline-xl": ["36px", {
          lineHeight: "1.3",
          fontWeight: "600",
        }],
        "display-lg-mobile": ["40px", {
          lineHeight: "1.2",
          letterSpacing: "-0.01em",
          fontWeight: "700",
        }],
        "label-md": ["14px", {
          lineHeight: "1",
          letterSpacing: "0.05em",
          fontWeight: "600",
        }],
        "body-md": ["16px", {
          lineHeight: "1.6",
          fontWeight: "400",
        }],
        "label-sm": ["12px", {
          lineHeight: "1.0",
          letterSpacing: "0.1em",
          fontWeight: "600",
        }],
      },
    },
  },
  plugins: [],
}
